packages:
  - "apps/*"
  - "packages/*"
  - "features/*"
  - "tooling/*"

catalog:
  "@types/node": ^22.0.0
  react: 19.0.0-rc-d025ddd3-20240722
  react-dom: 19.0.0-rc-d025ddd3-20240722
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.5.4
  next: 15.0.0-canary.92
