import type { Metadata } from "next";
import type { ReactNode } from "react";

import localFont from "next/font/local";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

export const metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
} satisfies Metadata;

const MainLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html lang="en">
			<body className={geistSans.variable} style={{ fontFamily: "var(--font-geist-sans)" }}>
				{children}
			</body>
		</html>
	);
};

export default MainLayout;
